version: '3.8'

services:
  tooltracker:
    image: ghcr.io/d-kholin/tooltracker/tooltracker:latest
    ports:
      - "5000:5000"
    volumes:
      - tooltracker_data:/app/data

volumes:
  tooltracker_data:
    driver: local
